name: CI

on:
    push:
      branches: [main]
    pull_request:
      branches:
        - main
       
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Use Node.js 21.x
          uses: actions/setup-node@v4
          with:
            node-version: 21.x

        - name: Install deps
          run: npm install

        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env:
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }} #must add secret in github repository(secrets and variables in sidebar), 
                                                              #obtained hook from render settings (also change out deploy to off once setup)
          run: |
            curl "$DEPLOY_URL"

            